[package]
name = "zennolab-products-searcher"
version = "0.1.0"
description = "ZennoLab products searcher."
authors = ["Yuriy Zymlex <www.zymlex.com>", "ZennoHelpers <github.com/ZennoHelpers>"]
edition = "2024"
resolver = "3"
autobins = false
autoexamples = false
autotests = false
autobenches = false

[[example]]
name = "usage"
required-features = []

[dependencies]
windows-registry = "0.5"
thiserror = "2.0"
serde = { version = "1.0", features = ["derive"], optional = true }
log = "0.4"

[features]
default = []
serde = ["dep:serde"]

[dev-dependencies]
env_logger = "0.11"